// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeomh2MRxtXi9C5lelb5XdLk-31ijhMN4',
    appId: '1:1049467164942:web:5f53e0373b2ee342301f5f',
    messagingSenderId: '1049467164942',
    projectId: 'smartscope-79619',
    authDomain: 'smartscope-79619.firebaseapp.com',
    storageBucket: 'smartscope-79619.firebasestorage.app',
    measurementId: 'G-RDY3V5CQXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJ_3_0Vj5x7KjtvgE3WX6cY9HwZzXddo',
    appId: '1:1049467164942:android:4eb1c03ed303698a301f5f',
    messagingSenderId: '1049467164942',
    projectId: 'smartscope-79619',
    storageBucket: 'smartscope-79619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXgUah2QEFisNNm3BmL51YhbfTN8nzlc',
    appId: '1:1049467164942:ios:c6a40b3febb27152301f5f',
    messagingSenderId: '1049467164942',
    projectId: 'smartscope-79619',
    storageBucket: 'smartscope-79619.firebasestorage.app',
    iosBundleId: 'com.example.smartscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXgUah2QEFisNNm3BmL51YhbfTN8nzlc',
    appId: '1:1049467164942:ios:c6a40b3febb27152301f5f',
    messagingSenderId: '1049467164942',
    projectId: 'smartscope-79619',
    storageBucket: 'smartscope-79619.firebasestorage.app',
    iosBundleId: 'com.example.smartscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeomh2MRxtXi9C5lelb5XdLk-31ijhMN4',
    appId: '1:1049467164942:web:ee894fb875f6e4fb301f5f',
    messagingSenderId: '1049467164942',
    projectId: 'smartscope-79619',
    authDomain: 'smartscope-79619.firebaseapp.com',
    storageBucket: 'smartscope-79619.firebasestorage.app',
    measurementId: 'G-BKFY9J1TEZ',
  );

}